version: '3.9'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: eckmeck
      POSTGRES_DB: bikefit
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:eckmeck@db:5432/bikefit
    ports:
      - "3000:3000"
    entrypoint: ["/bin/sh", "-c", "npx prisma migrate deploy && npm run start"]
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./ssl/certs:/etc/letsencrypt
      - ./ssl/webroot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - app-network

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./ssl/certs:/etc/letsencrypt
      - ./ssl/webroot:/var/www/certbot
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email ormonov31261@gmail.com --agree-tos --no-eff-email -d bikefit.kg -d www.bikefit.kg --force-renewal

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge